# Generated by Django 3.0.5 on 2020-05-06 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200506_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_photo',
            field=models.ImageField(blank=True, upload_to='book-image/%d/%m/%Y/'),
        ),
    ]
