# Generated by Django 3.0.5 on 2020-05-27 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_book_date_here'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_photo',
            field=models.ImageField(blank=True, null=True, upload_to='book-image/%d/%m/%Y/'),
        ),
    ]
