# Generated by Django 3.0.5 on 2020-05-27 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20200527_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='due_back',
            field=models.DateField(blank=True, help_text='Enter a date between now and 4 weeks (default 3).', null=True),
        ),
    ]
