# Generated by Django 3.0.5 on 2020-05-28 19:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20200527_1803'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='book',
            name='date_here',
            field=models.DateField(default=datetime.date(2020, 5, 28)),
        ),
    ]
