# Generated by Django 3.0.5 on 2020-05-29 18:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20200528_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_here',
            field=models.DateField(default=datetime.date(2020, 5, 29)),
        ),
    ]
