# Generated by Django 3.0.5 on 2020-06-03 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20200529_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_here',
            field=models.DateField(default=datetime.date(2020, 6, 3)),
        ),
    ]
